parameters:
    locale: 'en'
    imdb_api-key: '28a104cc'
    imdb_url: 'http://www.omdbapi.com/'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\ImdbService:
        arguments:
            $imdbApiKey: '%imdb_api-key%'
            $imdbUrl: '%imdb_url%'
            $entityManager: '@doctrine.orm.entity_manager'
